/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomer;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Airplane;
import Business.CustomerDirectory;
import Business.Flight;
import Business.ScheduleFlight;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class SearchFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomer
     */
    private AirlinerDirectory airlinerdirectory;
    private JPanel CardSequenceJPanel;
    private ArrayList <Flight> flightList;
    private ScheduleFlight scheduleflight;
    private ArrayList <Flight> scheduleList;
    private CustomerDirectory customerdirectory;
    public SearchFlightJPanel(JPanel CardSequenceJPanel, AirlinerDirectory airlinerdirectory, 
            ScheduleFlight scheduleflight) {
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airlinerdirectory = airlinerdirectory;
        this.scheduleflight = scheduleflight;
        this.customerdirectory = customerdirectory;
        scheduleList = scheduleflight.getSelectedFlightList();
        flightList = new ArrayList<>();
        for(Airliner airliner : airlinerdirectory.getAirlinerList()){
            for(Airplane airplane : airliner.getAirplaneDirectory().getAirplaneList()){
                for(Flight flight : airplane.getFlightdirectory().getFlightList() ){
                    flightList.add(flight);
                }
            }
        }
        initComponents();
        SimpleDateFormat f = new SimpleDateFormat ("yyyy-MM-dd HH:mm");
        
        populate();
        populate1();
    }
    
    public void populate(){
        sourceComboBox.removeAllItems();
        ArrayList<String> source = new ArrayList<>();
        for(Flight flight : flightList){
            if (!source.contains(flight.getfLocation())){
                source.add(flight.getfLocation());
            }
        }
        for (String s : source){
            sourceComboBox.addItem(s);
        }
    }
    
    public void populate1(){
        destinationComboBox.removeAllItems();
        ArrayList<String> destination = new ArrayList<>();
        for(Flight flight : flightList){
            if (!destination.contains(flight.gettLocation())){
                destination.add(flight.gettLocation());
            }
        }
        for (String s : destination){
            destinationComboBox.addItem(s);
        }
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceComboBox = new javax.swing.JComboBox();
        destinationComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        sourceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        destinationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Source:");

        jLabel2.setText("Destination:");

        jLabel3.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel3.setText("Search The Flight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destinationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(destinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addGap(98, 98, 98))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (Flight flight : flightList){
            if ( flight.getfLocation().equals(sourceComboBox.getSelectedItem())   
                    & flight.gettLocation().equals(destinationComboBox.getSelectedItem())){
                scheduleList.add(flight);
            }
        }
        if(scheduleList.isEmpty()){
            JOptionPane.showMessageDialog(null, "There is no appropriate flight");
        }else{
            ViewScheduledFlightJPanel vsfjp = new ViewScheduledFlightJPanel(CardSequenceJPanel, scheduleflight);
            CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
            CardSequenceJPanel.add("viewscheduleflight",vsfjp); 
            layout.next(CardSequenceJPanel);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox destinationComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox sourceComboBox;
    // End of variables declaration//GEN-END:variables
}
