/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirliner;

import Business.AirlinerDirectory;
import Business.Airliner;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author jhalak
 */
public class CreateNewAirlinerJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AirlinerDirectory airlinerDirectory;
    //private TravelAgency airlinerDirectory;

    /**
     * Creates new form CreateNewAirlinerJPanel
     */
    public CreateNewAirlinerJPanel(JPanel userProcessContainer, AirlinerDirectory airlineDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.airlinerDirectory = airlineDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAirlinerId = new javax.swing.JLabel();
        lblAirlinerName = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtAirlinerName = new javax.swing.JTextField();
        txtAirlinerId = new javax.swing.JTextField();
        banner = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblManufacturer = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAirlinerId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAirlinerId.setForeground(new java.awt.Color(102, 0, 0));
        lblAirlinerId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAirlinerId.setText("Airliner Id:");
        add(lblAirlinerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 94, -1, -1));

        lblAirlinerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAirlinerName.setForeground(new java.awt.Color(102, 0, 0));
        lblAirlinerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAirlinerName.setText("Airliner Name:");
        add(lblAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 136, -1, -1));

        lbladdress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbladdress.setForeground(new java.awt.Color(102, 0, 0));
        lbladdress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbladdress.setText("Address:");
        add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 180, -1, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 174, 114, -1));
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 136, 114, -1));
        add(txtAirlinerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 91, 114, -1));

        banner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        banner.setForeground(new java.awt.Color(0, 51, 102));
        banner.setText("Create Airliner");
        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 22, 157, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 0, 0));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 260, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setForeground(new java.awt.Color(102, 0, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 260, 87, -1));

        lblManufacturer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblManufacturer.setForeground(new java.awt.Color(102, 0, 0));
        lblManufacturer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufacturer.setText("Manufacturer:");
        add(lblManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 225, -1, -1));
        add(txtManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 222, 114, -1));
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkAirlinerDirectory(String airlinerId) {
        String airlinerIdFromList;
        for (Airliner ad : airlinerDirectory.getAirlinersDirectory()) {
            airlinerIdFromList = ad.getAirLinerId();

            if (airlinerIdFromList.equals(airlinerId)) {
                return true;
            }
        }
        return false;
    }


    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String airlinerId = txtAirlinerId.getText();
        String airlinerName = txtAirlinerName.getText();
        String manufacurerName = txtManufacturer.getText();
        String address = txtAddress.getText();

        if (!airlinerId.isEmpty() && !airlinerName.isEmpty()
                && !manufacurerName.isEmpty() && !address.isEmpty()) {
            boolean isAirlinerName = containsString(airlinerName);
            boolean isManufacturerName = containsString(manufacurerName);
            if (validateName(isAirlinerName) && validateName(isManufacturerName)) {
                if (!checkAirlinerDirectory(airlinerId)) {
                    Airliner airliner = airlinerDirectory.addAirliner();
                    airliner.setAirLinerId(airlinerId);
                    airliner.setAirlinerName(airlinerName);
                    airliner.setAddress(address);
                    airliner.setManufacturerName(manufacurerName);

                    JOptionPane.showMessageDialog(null, "Airliner successfully created!");
                } else {
                    JOptionPane.showMessageDialog(null, "Airliner ID already exist,please enter some another ID");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter values for empty fields");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public boolean containsString(String s) {

        if (s != null && !s.isEmpty()) {
            for (char c : s.toCharArray()) {
                if (Character.isDigit(c)) {
                    return false;
                }
            }
        }

        return true;
    }

    public boolean validateName(boolean isName) {
        if (!isName) {
            JOptionPane.showMessageDialog(null, "This text Field cannot contain number");
            return false;
        }
        return true;
    }


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinerJPanel manageAirlinerJpanel = (ManageAirlinerJPanel) component;
        manageAirlinerJpanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAirlinerId;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAirlinerId;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtManufacturer;
    // End of variables declaration//GEN-END:variables
}
