/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.FlightSchedule;
import Business.MasterSchedule;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhalak
 */
public class ManageFlightsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private MasterSchedule masterScheduleDirectory;

    /**
     * Creates new form ManageFlightsJPanel
     */
    public ManageFlightsJPanel(JPanel userProcessContainer, MasterSchedule masterScheduleDirectory) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.masterScheduleDirectory = masterScheduleDirectory;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Banner = new javax.swing.JLabel();
        lblFlightId = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblDepartureDate = new javax.swing.JLabel();
        txtFlightId = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtAirlinerName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnViewFlightDetails = new javax.swing.JButton();
        lblTimeOfDay1 = new javax.swing.JLabel();
        txtDepartureTime = new javax.swing.JTextField();
        lblAirlinerName = new javax.swing.JLabel();
        txtTimeOfDay = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banner.setForeground(new java.awt.Color(0, 51, 102));
        Banner.setText("CREATE FLIGHT");
        add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 19, 175, -1));

        lblFlightId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFlightId.setForeground(new java.awt.Color(102, 0, 0));
        lblFlightId.setText("Flight ID:");
        add(lblFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 74, -1, -1));

        lblModelNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblModelNumber.setForeground(new java.awt.Color(102, 0, 0));
        lblModelNumber.setText("              Price:");
        add(lblModelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 118, 87, -1));

        lblSource.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSource.setForeground(new java.awt.Color(102, 0, 0));
        lblSource.setText("Source:");
        add(lblSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 162, -1, -1));

        lblDestination.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDestination.setForeground(new java.awt.Color(102, 0, 0));
        lblDestination.setText("Destination:");
        add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 204, -1, -1));

        lblDepartureDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDepartureDate.setForeground(new java.awt.Color(102, 0, 0));
        lblDepartureDate.setText("   Departure Time:");
        add(lblDepartureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 277, -1, -1));
        add(txtFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 71, 114, -1));
        add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 201, 114, -1));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 115, 114, -1));
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 159, 114, -1));
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 321, 114, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 417, 121, -1));

        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(102, 0, 0));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 376, -1, -1));

        btnViewFlightDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewFlightDetails.setForeground(new java.awt.Color(102, 0, 0));
        btnViewFlightDetails.setText("View Details >>");
        btnViewFlightDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightDetailsActionPerformed(evt);
            }
        });
        add(btnViewFlightDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 376, -1, -1));

        lblTimeOfDay1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimeOfDay1.setForeground(new java.awt.Color(102, 0, 0));
        lblTimeOfDay1.setText("Time Of Day:");
        add(lblTimeOfDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 242, -1, -1));
        add(txtDepartureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 277, 114, -1));

        lblAirlinerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAirlinerName.setForeground(new java.awt.Color(102, 0, 0));
        lblAirlinerName.setText("Airliner Name:");
        add(lblAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 321, -1, -1));
        add(txtTimeOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 239, 114, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewFlightDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightDetailsActionPerformed
        // TODO add your handling code here:
        ViewFlightJPanel viewAirlinerPanel = new ViewFlightJPanel(userProcessContainer, masterScheduleDirectory);
        userProcessContainer.add("ViewFlightsJPanel", viewAirlinerPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnViewFlightDetailsActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat parser = new SimpleDateFormat("MM-dd-yyyy hh:mm");
        String flightId = txtFlightId.getText();
        int price = 0;
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        String timeOfDay = txtTimeOfDay.getText();
        Date departureTime;
        boolean isSource = containsString(source);
        boolean isDestination = containsString(destination);
        boolean isTimeOfDay = containsString(timeOfDay);
        String airlinerName=txtAirlinerName.getText();

        try {
            try {
                price = Integer.parseInt(txtPrice.getText());
                departureTime = parser.parse(txtDepartureTime.getText());
                if (!flightId.isEmpty() && price != 0
                        && !source.isEmpty() && !destination.isEmpty() && !airlinerName.isEmpty()) {
                    if (!checkFlightsDirectory(flightId)) {

                        if (validateSourceOrDestinationName(isSource) && validateSourceOrDestinationName(isDestination)) {
                            FlightSchedule flights = masterScheduleDirectory.addFlights();
                            flights.setFlightId(flightId);
                            flights.setDestination(destination);
                            flights.setSource(source);
                            flights.setFlightDate(departureTime);
                            flights.setTimeOfDay(timeOfDay);
                            flights.setPrice(price);
                            flights.setAirlinerName(airlinerName);
                            JOptionPane.showMessageDialog(null, "Flight successfully created!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Flight ID already exist,please enter some another ID");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter values for empty fields");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please proper integer value for price");

            } catch (ParseException exception) {
                JOptionPane.showMessageDialog(null, "Please enter the date for  departure time in the correct format:"
                        + " mm-dd-yyyy hh:mm");
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Flight cannot be created!");

        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private boolean checkFlightsDirectory(String airlinerId) {
        String airlinerIdFromList;
        for (FlightSchedule ad : masterScheduleDirectory.getMasterFlightSchedules()) {
            airlinerIdFromList = ad.getFlightId();

            if (airlinerIdFromList.equals(airlinerId)) {
                return true;
            }
        }
        return false;
    }

    public boolean containsString(String s) {

        if (s != null && !s.isEmpty()) {
            for (char c : s.toCharArray()) {
                if (Character.isDigit(c)) {
                    return false;
                }
            }
        }

        return true;
    }

    public boolean validateSourceOrDestinationName(boolean isBankName) {
        if (!isBankName) {
            JOptionPane.showMessageDialog(null, "Source or destination contains number");
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnViewFlightDetails;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JLabel lblDepartureDate;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblFlightId;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTimeOfDay1;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtDepartureTime;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFlightId;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTimeOfDay;
    // End of variables declaration//GEN-END:variables

}
