/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.MasterSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhalak
 */
public class ManageAirlinerJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AirlinerDirectory airlinerDirectory;
    private MasterSchedule masterScheduleDirectory;
    private TravelAgency travelAgency;
    DefaultTableModel dtm;

    /**
     * Creates new form ManageTravelAgencyJPanel
     */
    public ManageAirlinerJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
        //this.masterScheduleDirectory= masterScheduleDirectory;
        //populateTable();

    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblAirlinersList.getModel();
        dtm.setRowCount(0);
        displayValuesInTable(dtm);
    }

    private void displayValuesInTable(DefaultTableModel dtm) {
        for (Airliner ad : travelAgency.getAirlinerDirectory().getAirlinersDirectory()) {
            Object row[] = new Object[4];
            row[0] = ad;
            row[1] = ad.getAirlinerName();
            row[2] = ad.getManufacturerName();
            row[3] = ad.getAddress();
            dtm.addRow(row);

        }
    }

    public void populateSecondaryTable(String airline) {
        DefaultTableModel dtm = (DefaultTableModel) tblChildAirlinerList.getModel();
        dtm.setRowCount(0);
        for (Airliner ad : travelAgency.getAirlinerDirectory().getAirlinersDirectory()) {

            if (ad.getAirlinerName().equals(airline)) {
                Object row[] = new Object[4];
                row[0] = ad;
                row[1] = ad.getAddress();
                row[2] = ad.getManufacturerName();
                dtm.addRow(row);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblAirlinersList = new javax.swing.JTable();
        btnViewAirliner = new javax.swing.JButton();
        btnCreateAirliner = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtSearchAirliner = new javax.swing.JTextField();
        lblAirlinerName = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        Banner = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChildAirlinerList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAirlinersList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblAirlinersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Id", " Airliner Name", " Manufacturer", " Address"
            }
        ));
        jScrollPane2.setViewportView(tblAirlinersList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 64, 620, 155));

        btnViewAirliner.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewAirliner.setForeground(new java.awt.Color(102, 0, 0));
        btnViewAirliner.setText("View Airliner >>");
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });
        add(btnViewAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 477, 135, -1));

        btnCreateAirliner.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreateAirliner.setForeground(new java.awt.Color(102, 0, 0));
        btnCreateAirliner.setText("Create Airliner >>");
        btnCreateAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlinerActionPerformed(evt);
            }
        });
        add(btnCreateAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 436, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 477, -1, -1));
        add(txtSearchAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 255, 115, -1));

        lblAirlinerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAirlinerName.setForeground(new java.awt.Color(102, 0, 0));
        lblAirlinerName.setText("Airliner Name:");
        add(lblAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(102, 0, 0));
        btnSearch.setText("Search >>");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 304, -1, -1));

        Banner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banner.setForeground(new java.awt.Color(0, 51, 102));
        Banner.setText("MANAGE AIRLINERS");
        add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 19, 200, -1));

        tblChildAirlinerList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblChildAirlinerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Id", "  Address", "Manufacturer"
            }
        ));
        jScrollPane3.setViewportView(tblChildAirlinerList);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 255, 410, 126));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("List All Airliners");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        // TODO add your handling code here
        int selectedRow = tblChildAirlinerList.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Airliner airliner = (Airliner) tblChildAirlinerList.getValueAt(selectedRow, 0);
            ViewAirlinerJPanel viewAirlinerPanel = new ViewAirlinerJPanel(userProcessContainer, airliner, travelAgency.getMasterScheduleDirectory());
            userProcessContainer.add("ViewAirlinerJPanel", viewAirlinerPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    private void btnCreateAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlinerActionPerformed
        // TODO add your handling code here:
        CreateNewAirlinerJPanel createNewAirlinerPanel = new CreateNewAirlinerJPanel(userProcessContainer, travelAgency.getAirlinerDirectory());
        userProcessContainer.add("CreateNewAirlinerJPanel", createNewAirlinerPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateAirlinerActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String airLinerName = txtSearchAirliner.getText();
        if (!airLinerName.isEmpty()) {
            populateSecondaryTable(airLinerName);
        } else {
            JOptionPane.showMessageDialog(null, "Please enter airliner name to be searched");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAirliner;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JTable tblAirlinersList;
    private javax.swing.JTable tblChildAirlinerList;
    private javax.swing.JTextField txtSearchAirliner;
    // End of variables declaration//GEN-END:variables
}
