/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.FlightSchedule;
import Business.MasterSchedule;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhalak
 */
public class ViewFlightJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Airliner airliner;
    private AirlinerDirectory airlinerDirectory;
    private MasterSchedule masterScheduleDirectory;
    FlightSchedule airplanesDetails;

    /**
     * Creates new form ViewAirlinerJPanel
     */
    public ViewFlightJPanel(JPanel userProcessContainer, MasterSchedule masterScheduleDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.masterScheduleDirectory = masterScheduleDirectory;

        populateTable();
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblFlightDetails.getModel();
        dtm.setRowCount(0);
        displayValuesInTable(dtm);
    }

    private void displayValuesInTable(DefaultTableModel dtm) {
        for (FlightSchedule ad : masterScheduleDirectory.getMasterFlightSchedules()) {
            Object row[] = new Object[3];
            row[0] = ad;
            row[1] = ad.getSource();
            row[2] = ad.getDestination();

            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblFlightDetails = new javax.swing.JTable();
        Banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFlightId = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtTimeOfDay = new javax.swing.JTextField();
        lblTimeOfDay = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblFlightId = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFlightDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblFlightDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "   Flight Id", "  Source", "  Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblFlightDetails);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 66, 579, 155));

        Banner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banner.setForeground(new java.awt.Color(0, 51, 102));
        Banner.setText("VIEW ALL FLIGHTS");
        add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 16, 220, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("List All Flights");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 41, 90, -1));

        txtFlightId.setEnabled(false);
        add(txtFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 255, 201, -1));

        txtPrice.setEnabled(false);
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 299, 201, -1));

        txtSource.setEnabled(false);
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 349, 201, -1));

        txtDestination.setEnabled(false);
        add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 391, 201, -1));

        txtTimeOfDay.setEnabled(false);
        add(txtTimeOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 429, 201, -1));

        lblTimeOfDay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimeOfDay.setForeground(new java.awt.Color(102, 0, 0));
        lblTimeOfDay.setText("Time Of Day:");
        add(lblTimeOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 432, -1, -1));

        lblDestination.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDestination.setForeground(new java.awt.Color(102, 0, 0));
        lblDestination.setText("Destination:");
        add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 394, -1, -1));

        lblSource.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSource.setForeground(new java.awt.Color(102, 0, 0));
        lblSource.setText("Source:");
        add(lblSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 352, -1, -1));

        lblModelNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblModelNumber.setForeground(new java.awt.Color(102, 0, 0));
        lblModelNumber.setText("               Price:");
        add(lblModelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 302, 80, -1));

        lblFlightId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFlightId.setForeground(new java.awt.Color(102, 0, 0));
        lblFlightId.setText("Flight ID:");
        add(lblFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 258, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 499, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setForeground(new java.awt.Color(102, 0, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 499, -1, -1));

        btnViewDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(102, 0, 0));
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 254, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(102, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 499, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(102, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 299, 101, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFlightDetails.getSelectedRow();
        if (selectedRow >= 0) {

            airplanesDetails = (FlightSchedule) tblFlightDetails.getValueAt(selectedRow, 0);
            txtFlightId.setText(airplanesDetails.getFlightId());
            txtPrice.setText(String.valueOf(airplanesDetails.getPrice()));
            txtSource.setText(airplanesDetails.getSource());
            txtDestination.setText(airplanesDetails.getDestination());
            txtTimeOfDay.setText(airplanesDetails.getTimeOfDay());

        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }

    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //txtFlightId.setEnabled(true);
        txtPrice.setEnabled(true);
        txtSource.setEnabled(true);
        txtDestination.setEnabled(true);
        txtTimeOfDay.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String flightId = txtFlightId.getText();
        int modelNumber = 0;
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        String timeOfDay = txtTimeOfDay.getText();

        boolean isSource = containsString(source);
        boolean isDestination = containsString(destination);
        boolean isTimeOfDay = containsString(timeOfDay);

        try {
            try {
                modelNumber = Integer.parseInt(txtPrice.getText());

                if (!flightId.isEmpty() && modelNumber != 0
                        && !source.isEmpty() && !destination.isEmpty()) {

                    if (validateSourceOrDestinationName(isSource) && validateSourceOrDestinationName(isDestination)) {
                        //FlightSchedule flights = masterScheduleDirectory.addFlights();
                        airplanesDetails.setFlightId(txtFlightId.getText());
                        airplanesDetails.setDestination(txtDestination.getText());
                        airplanesDetails.setSource(txtSource.getText());
                        airplanesDetails.setTimeOfDay(txtTimeOfDay.getText());
                        airplanesDetails.setPrice(modelNumber);
                        JOptionPane.showMessageDialog(null, "Flight successfully created!");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Please enter values for empty fields");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please proper integer value for model number and seats availability");

            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Flight cannot be created!");

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFlightDetails.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the account details", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                FlightSchedule account = (FlightSchedule) tblFlightDetails.getValueAt(selectedRow, 0);
                masterScheduleDirectory.deleteAccount(account);
                populateTable();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public boolean containsString(String s) {

        if (s != null && !s.isEmpty()) {
            for (char c : s.toCharArray()) {
                if (Character.isDigit(c)) {
                    return false;
                }
            }
        }

        return true;
    }

    public boolean validateSourceOrDestinationName(boolean isBankName) {
        if (!isBankName) {
            JOptionPane.showMessageDialog(null, "Source or destination contains number");
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblFlightId;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTimeOfDay;
    private javax.swing.JTable tblFlightDetails;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFlightId;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTimeOfDay;
    // End of variables declaration//GEN-END:variables
}
