/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirliner;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.MasterSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhalak
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Airliner airliner;
    private AirlinerDirectory airlinerDirectory;
    private MasterSchedule masterScheduleDirectory;
    

    /**
     * Creates new form ViewAirlinerJPanel
     */
    public ViewAirlinerJPanel(JPanel userProcessContainer, Airliner airline, MasterSchedule masterScheduleDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.airliner = airline;
        this.masterScheduleDirectory=masterScheduleDirectory;
        populateAccountDetails();
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);

    }

    
    
    
    
    private void populateAccountDetails() {
        txtAirlinerId.setText(airliner.getAirLinerId());
        txtAirlinerName.setText(airliner.getAirlinerName());
        txtManufacturer.setText(airliner.getManufacturerName());
        txtAddress.setText(airliner.getAddress());
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JLabel();
        lblAirlinerId = new javax.swing.JLabel();
        lblAirlinerName = new javax.swing.JLabel();
        lbladdress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtAirlinerName = new javax.swing.JTextField();
        txtAirlinerId = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnManageAllFlights = new javax.swing.JButton();
        lblManufacturer = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        banner.setForeground(new java.awt.Color(0, 51, 102));
        banner.setText("View Airliner");
        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 34, 171, -1));

        lblAirlinerId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAirlinerId.setForeground(new java.awt.Color(102, 0, 0));
        lblAirlinerId.setText("Airliner Id:");
        add(lblAirlinerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 106, -1, -1));

        lblAirlinerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAirlinerName.setForeground(new java.awt.Color(102, 0, 0));
        lblAirlinerName.setText("Airliner Name:");
        add(lblAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 151, -1, -1));

        lbladdress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbladdress.setForeground(new java.awt.Color(102, 0, 0));
        lbladdress.setText("Address:");
        add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 189, -1, -1));

        txtAddress.setEnabled(false);
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 186, 86, -1));

        txtAirlinerName.setEnabled(false);
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 148, 86, -1));

        txtAirlinerId.setEnabled(false);
        add(txtAirlinerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 103, 86, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 284, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setForeground(new java.awt.Color(102, 0, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 284, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(102, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 284, 84, -1));

        btnManageAllFlights.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageAllFlights.setText("Manage All Flights");
        btnManageAllFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAllFlightsActionPerformed(evt);
            }
        });
        add(btnManageAllFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 362, 173, -1));

        lblManufacturer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblManufacturer.setForeground(new java.awt.Color(102, 0, 0));
        lblManufacturer.setText("Manufacturer:");
        add(lblManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 223, -1, -1));

        txtManufacturer.setEnabled(false);
        add(txtManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 220, 86, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAllFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAllFlightsActionPerformed
        // TODO add your handling code here:
       
            ManageFlightsJPanel viewAirlinerPanel = new ManageFlightsJPanel(userProcessContainer,masterScheduleDirectory);
            userProcessContainer.add("ManageFlightsJPanel", viewAirlinerPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);


    }//GEN-LAST:event_btnManageAllFlightsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray=userProcessContainer.getComponents();
        Component component=componentArray[componentArray.length-1];
        ManageAirlinerJPanel manageAirlinerJpanel=(ManageAirlinerJPanel) component;
        manageAirlinerJpanel.populateTable();
       
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //txtAirlinerId.setEnabled(true);
        txtAirlinerName.setEnabled(true);
        txtManufacturer.setEnabled(true);
        txtAddress.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String airlinerId = txtAirlinerId.getText();
        String airlinerName = txtAirlinerName.getText();
        String manufacurerName = txtManufacturer.getText();
        String address = txtAddress.getText();

        if (!airlinerId.isEmpty() && !airlinerName.isEmpty()
                && !manufacurerName.isEmpty() && !address.isEmpty()) {
 
                airliner.setAirLinerId(txtAirlinerId.getText());
                airliner.setAirlinerName(txtAirlinerName.getText());
                airliner.setAddress(txtAddress.getText());
                airliner.setManufacturerName(txtManufacturer.getText());
                btnSave.setEnabled(false);
                btnUpdate.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Airliner successfully created!");
             
        } else {
            JOptionPane.showMessageDialog(null, "Please enter values for empty fields");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private boolean checkAirlinerDirectory(String airlinerId) {
        String airlinerIdFromList;
        for (Airliner ad : airlinerDirectory.getAirlinersDirectory()) {
            airlinerIdFromList = ad.getAirLinerId();

            if (airlinerIdFromList.equals(airlinerId)) {
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageAllFlights;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAirlinerId;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAirlinerId;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtManufacturer;
    // End of variables declaration//GEN-END:variables
}
