/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Information.Data;
import Information.DrivData;
/**
 *
 * @author Administrator
 */
public class DrivInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form DrivInfoFrame
     */
    private Data data;
    private DrivData drivdata;
    public DrivInfoFrame(Data data) {
        initComponents();
        this.data = data;
        this.drivdata = data.getDrivata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drivSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        drivCreateBtn = new javax.swing.JButton();
        drivViewBtn = new javax.swing.JButton();
        drivExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drivCreateBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        drivCreateBtn.setForeground(new java.awt.Color(0, 51, 51));
        drivCreateBtn.setText("Create");
        drivCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivCreateBtnActionPerformed(evt);
            }
        });

        drivViewBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        drivViewBtn.setForeground(new java.awt.Color(0, 51, 51));
        drivViewBtn.setText("View");
        drivViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivViewBtnActionPerformed(evt);
            }
        });

        drivExit.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        drivExit.setForeground(new java.awt.Color(0, 51, 51));
        drivExit.setText("Exit");
        drivExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(drivCreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drivViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drivExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(drivCreateBtn)
                .addGap(56, 56, 56)
                .addComponent(drivViewBtn)
                .addGap(55, 55, 55)
                .addComponent(drivExit)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        drivSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        drivSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(drivSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drivCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivCreateBtnActionPerformed
        // TODO add your handling code here:
        DrivCreatePanel drivcreatepanel = new DrivCreatePanel(data);
        drivSplitPane1.setRightComponent(drivcreatepanel);
    }//GEN-LAST:event_drivCreateBtnActionPerformed

    private void drivViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivViewBtnActionPerformed
        // TODO add your handling code here:
        DrivViewPanel drivviewpanel = new DrivViewPanel(data);
        drivSplitPane1.setRightComponent(drivviewpanel);
    }//GEN-LAST:event_drivViewBtnActionPerformed

    private void drivExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_drivExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrivInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrivInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrivInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrivInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drivCreateBtn;
    private javax.swing.JButton drivExit;
    private javax.swing.JSplitPane drivSplitPane1;
    private javax.swing.JButton drivViewBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
