/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Information.Data;
import Information.MediData;
/**
 *
 * @author Administrator
 */
public class MediInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form MediInfoFrame
     */
    private Data data;
    private MediData medidata;
    public MediInfoFrame(Data data) {
        initComponents();
        this.medidata = data.getMedidata();
        this.data = data;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mediSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        mediCreateBtn = new javax.swing.JButton();
        mediViewBtn = new javax.swing.JButton();
        mediExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mediCreateBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        mediCreateBtn.setForeground(new java.awt.Color(0, 51, 51));
        mediCreateBtn.setText("Create");
        mediCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediCreateBtnActionPerformed(evt);
            }
        });

        mediViewBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        mediViewBtn.setForeground(new java.awt.Color(0, 51, 51));
        mediViewBtn.setText("View");
        mediViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediViewBtnActionPerformed(evt);
            }
        });

        mediExit.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        mediExit.setForeground(new java.awt.Color(0, 51, 51));
        mediExit.setText("Exit");
        mediExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mediCreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mediViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mediExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(mediCreateBtn)
                .addGap(56, 56, 56)
                .addComponent(mediViewBtn)
                .addGap(55, 55, 55)
                .addComponent(mediExit)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        mediSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        mediSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(mediSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mediCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediCreateBtnActionPerformed
        // TODO add your handling code here:
        MediCreatePanel medicreatepanel = new MediCreatePanel(data);
        mediSplitPane1.setRightComponent(medicreatepanel);
    }//GEN-LAST:event_mediCreateBtnActionPerformed

    private void mediViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediViewBtnActionPerformed
        // TODO add your handling code here:
        MediViewPanel mediviewpanel = new MediViewPanel(data);
        mediSplitPane1.setRightComponent(mediviewpanel);
    }//GEN-LAST:event_mediViewBtnActionPerformed

    private void mediExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_mediExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MediInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MediInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MediInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MediInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mediCreateBtn;
    private javax.swing.JButton mediExit;
    private javax.swing.JSplitPane mediSplitPane1;
    private javax.swing.JButton mediViewBtn;
    // End of variables declaration//GEN-END:variables
}
