/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Information.Data;
/**
 *
 * @author Administrator
 */
public class SavViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form SavViewPanel
     */
    public Data data;
    public SavViewPanel(Data data) {
        initComponents();
        displaySavInfo(data);
    }
    
    private void displaySavInfo(Data data){
        bankNameLabel.setText(data.getSavdata().getBankName());
        bankRouLabel.setText(data.getSavdata().getBankRouNum());
        bankAccNumLabel.setText(data.getSavdata().getBankAccNum());
        accBalLabel.setText(data.getSavdata().getAccountBal());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel0 = new javax.swing.JLabel();
        bankNameLabel = new javax.swing.JLabel();
        bankRouLabel = new javax.swing.JLabel();
        bankAccNumLabel = new javax.swing.JLabel();
        accBalLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel0.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel0.setText("View Your Saving Account Information");

        bankNameLabel.setText("jLable9");

        bankRouLabel.setText("jLabel10");

        bankAccNumLabel.setText("jLabel11");

        accBalLabel.setText("jLabel12");

        jLabel1.setText("Bank Name:");

        jLabel2.setText("Bank Routing Number:");

        jLabel3.setText("Bank Account Number:");

        jLabel4.setText("Account Balance:");

        jLabel5.setText("Account Type:");

        jLabel6.setText("Saving");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel0))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankNameLabel)
                            .addComponent(bankRouLabel)
                            .addComponent(bankAccNumLabel)
                            .addComponent(accBalLabel)
                            .addComponent(jLabel6))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel0)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bankNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(bankRouLabel)
                        .addGap(18, 18, 18)
                        .addComponent(bankAccNumLabel)
                        .addGap(18, 18, 18)
                        .addComponent(accBalLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accBalLabel;
    private javax.swing.JLabel bankAccNumLabel;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JLabel bankRouLabel;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
