package UserInterface.ManageFlight;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Business.Airplane;
import Business.Flight;
import Business.FlightDirectory;
import static UserInterface.MainFrame.showInt;
import static UserInterface.MainFrame.toInt;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class CreateNewFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewFlightJPanel
     */
    private Airplane airplane;
    private JPanel CardSequenceJPanel;
    private FlightDirectory flightdirectory;
    private Boolean have;
    public CreateNewFlightJPanel(JPanel CardSequenceJPanel, Airplane airplane, FlightDirectory flightdirectory) {
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.flightdirectory = flightdirectory;
        this.airplane = airplane;
        initComponents();
        airlinerName.setText(airplane.getAirlinerName());
        airplaneName.setText(airplane.getAirplaneName());
    }

    private void backAction(){
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length-1];
        ManageFlightsJPanel mf = (ManageFlightsJPanel) component;
        mf.populate();
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.show(CardSequenceJPanel, "manageflight");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        fName = new javax.swing.JTextField();
        fLocation = new javax.swing.JTextField();
        tLocation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dyear = new javax.swing.JTextField();
        dmonth = new javax.swing.JTextField();
        dday = new javax.swing.JTextField();
        dminute = new javax.swing.JTextField();
        dhour = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ayear = new javax.swing.JTextField();
        aminute = new javax.swing.JTextField();
        aday = new javax.swing.JTextField();
        amonth = new javax.swing.JTextField();
        ahour = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        airplaneName = new javax.swing.JTextField();
        airlinerName = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        jButton1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButton1.setText("<<  Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Flight Name:");

        jLabel2.setText("Source:");

        jLabel3.setText("Destination:");

        jLabel4.setText("Departure Date:");

        jLabel5.setText("Arrival Date:");

        jLabel6.setText("Year");

        jLabel7.setText("Month");

        jLabel8.setText("Day");

        jLabel9.setText("Hour");

        jLabel10.setText("Minute");

        aday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adayActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel11.setText("Create Flight");

        jLabel12.setText("Airplane Name:");

        jLabel13.setText("Airliner Name:");

        airplaneName.setEnabled(false);

        airlinerName.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ayear, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dyear, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(amonth, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(aday, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ahour, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(aminute, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dday, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(dhour, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(dminute, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel6)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel7)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel8)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel9)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel10))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fName)
                                    .addComponent(fLocation)
                                    .addComponent(tLocation)
                                    .addComponent(airplaneName)
                                    .addComponent(airlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(airlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(airplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dhour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dminute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ayear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ahour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aminute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(51, 51, 51)
                .addComponent(jButton3)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        have = true;
        if (fName.getText().isEmpty() || fLocation.getText().isEmpty() || tLocation.getText().isEmpty() ||
                dyear.getText().isEmpty() || dmonth.getText().isEmpty() ||
                dday.getText().isEmpty() || dhour.getText().isEmpty() || dminute.getText().isEmpty() ||
                dyear.getText().isEmpty() || dmonth.getText().isEmpty() || dday.getText().isEmpty() || 
                dhour.getText().isEmpty() || dminute.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill in the blank", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if(toInt(dyear.getText()) && toInt(dmonth.getText()) && toInt(dday.getText()) && toInt(dhour.getText()) &&
                toInt(dminute.getText()) && toInt(ayear.getText()) && toInt(amonth.getText()) && toInt(aday.getText()) && 
                toInt(ahour.getText()) && toInt(aminute.getText())){
            Calendar cal1 = Calendar.getInstance(); 
            cal1.set(Integer.parseInt(dyear.getText()), Integer.parseInt(dmonth.getText())-1, 1);
            int maxday1 = cal1.getActualMaximum(Calendar.DAY_OF_MONTH); 
            Calendar cal2 = Calendar.getInstance(); 
            cal2.set(Integer.parseInt(ayear.getText()), Integer.parseInt(amonth.getText())-1, 1);
            int maxday2 = cal2.getActualMaximum(Calendar.DAY_OF_MONTH); 
            Calendar dCal = Calendar.getInstance(); 
            dCal.set(Integer.parseInt(dyear.getText()), Integer.parseInt(dmonth.getText())-1, Integer.parseInt(dday.getText()),
                Integer.parseInt(dhour.getText()), Integer.parseInt(dminute.getText()));
            Calendar aCal = Calendar.getInstance(); 
            aCal.set(Integer.parseInt(ayear.getText()), Integer.parseInt(amonth.getText())-1, Integer.parseInt(aday.getText()),
                Integer.parseInt(ahour.getText()), Integer.parseInt(aminute.getText()));
            if(Integer.parseInt(dyear.getText()) >= 2018 && Integer.parseInt(ayear.getText()) >= 2018){
                if( Integer.parseInt(dmonth.getText()) <= 12 && Integer.parseInt(dmonth.getText()) > 0 &&
                    Integer.parseInt(amonth.getText()) <= 12 && Integer.parseInt(amonth.getText()) > 0 ){
                    if(Integer.parseInt(dday.getText()) <= maxday1 && Integer.parseInt(aday.getText()) <= maxday2 &&
                        Integer.parseInt(dday.getText()) > 0 && Integer.parseInt(aday.getText()) > 0){
                        if(Integer.parseInt(dhour.getText()) < 24 && Integer.parseInt(ahour.getText()) < 24){
                            if(Integer.parseInt(dminute.getText()) < 60 && Integer.parseInt(aminute.getText()) < 60){
                                if(dCal.getTime().getTime() < aCal.getTime().getTime()){
                                    for(Flight flighttest : flightdirectory.getFlightList()){
                                        if( ((flighttest.getdTime().getTime() <= dCal.getTime().getTime()) & 
                                                (flighttest.getaTime().getTime() >= dCal.getTime().getTime()))  ||
                                                ((flighttest.getdTime().getTime() <= aCal.getTime().getTime()) & 
                                                (flighttest.getaTime().getTime() >= aCal.getTime().getTime()))  ||
                                                ((flighttest.getdTime().getTime() >= dCal.getTime().getTime()) & 
                                                (flighttest.getaTime().getTime() <= aCal.getTime().getTime())) 
                                                ){
                                            have = false;
                                        }
                                    }
                                    if (have == true){
                                        Flight flight = flightdirectory.add();
                                        flight.setAirlinerName(airplane.getAirlinerName());
                                        flight.setAirplaneName(airplane.getAirplaneName());
                                        flight.setFlightName(fName.getText());
                                        flight.setfLocation(fLocation.getText());
                                        flight.settLocation(tLocation.getText());
                                        //Date d = new Date();
                                        //d.setYear(Integer.parseInt(dyear.getText())-1899);
                                        //d.setMonth(Integer.parseInt(dmonth.getText())-12);
                                        //d.setDate(Integer.parseInt(dday.getText())-maxday1);
                                        //d.setHours(Integer.parseInt(dhour.getText()));
                                        //d.setMinutes(Integer.parseInt(dminute.getText()));
                                        flight.setdTime(dCal.getTime());
                                        //Date a = new Date();
                                        //a.setYear(Integer.parseInt(ayear.getText())-1899);
                                        //a.setMonth(Integer.parseInt(amonth.getText())-12);
                                        //a.setDate(Integer.parseInt(aday.getText())-maxday2);
                                        //a.setHours(Integer.parseInt(ahour.getText()));
                                        //a.setMinutes(Integer.parseInt(aminute.getText()));
                                        flight.setaTime(aCal.getTime());
                                        JOptionPane.showMessageDialog(null, "Flight created successfully");
                                    }else{
                                        JOptionPane.showMessageDialog(null, "The flight has been assigned during this time", "Warning",JOptionPane.WARNING_MESSAGE);
                                    }
                                }else{
                                    JOptionPane.showMessageDialog(null, "departure time must be ealer than arrival time", "Warning",JOptionPane.WARNING_MESSAGE);
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "Minute can not be greater than 60", "Warning", JOptionPane.WARNING_MESSAGE);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Hour can not be greater than 23", "Warning", JOptionPane.WARNING_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Please enter the valid day", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Month must be between 1 and 12", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Year can not be less than 2018", "Warning", JOptionPane.WARNING_MESSAGE);
            }       
        }else{
            showInt(dyear.getText());
            showInt(dmonth.getText());
            showInt(dday.getText());
            showInt(dhour.getText());
            showInt(dminute.getText());
            showInt(ayear.getText());
            showInt(amonth.getText());
            showInt(aday.getText());
            showInt(ahour.getText());
            showInt(aminute.getText());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aday;
    private javax.swing.JTextField ahour;
    private javax.swing.JTextField airlinerName;
    private javax.swing.JTextField airplaneName;
    private javax.swing.JTextField aminute;
    private javax.swing.JTextField amonth;
    private javax.swing.JTextField ayear;
    private javax.swing.JTextField dday;
    private javax.swing.JTextField dhour;
    private javax.swing.JTextField dminute;
    private javax.swing.JTextField dmonth;
    private javax.swing.JTextField dyear;
    private javax.swing.JTextField fLocation;
    private javax.swing.JTextField fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tLocation;
    // End of variables declaration//GEN-END:variables
}
