/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.mangeTravelAgency;

import Business.Airliner;
import Business.FlightSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhalak
 */
public class TravelAgencyJPanel extends javax.swing.JPanel {

    private TravelAgency travelAgency;
    private JPanel userProcessContainer;

    /**
     * Creates new form TravelAgencyJPanel
     */
    public TravelAgencyJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
    }

    public void populateTable(String source, String destination, String timeOfDay, Date flightDate) {

        DefaultTableModel dtm = (DefaultTableModel) tblSearchFlightList.getModel();
        dtm.setRowCount(0);
        SimpleDateFormat parser = new SimpleDateFormat("MM-dd-yyyy");
        ArrayList<FlightSchedule> flightScheduleArrayList = travelAgency.getMasterScheduleDirectory().getMasterFlightSchedules();
        for (FlightSchedule ad : flightScheduleArrayList) {

            if (ad.getSource().equalsIgnoreCase(source)
                    && ad.getDestination().equalsIgnoreCase(destination)
                    && ad.getTimeOfDay().equalsIgnoreCase(timeOfDay)
                    && parser.format(ad.getFlightDate()).equalsIgnoreCase(txtDate.getText())) {
                Object row[] = new Object[6];
                row[0] = ad;
                row[1] = ad.getSource();
                row[2] = ad.getDestination();
                row[3] = ad.getFlightDate();
                row[4] = ad.getTimeOfDay();
                row[5] = ad.getPrice();
                dtm.addRow(row);
            }

        }

        if (dtm.getRowCount() < 1) {
            JOptionPane.showMessageDialog(null, "There are no flights available for a given search");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSource = new javax.swing.JTextField();
        lblSource = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtTimeOfDay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchFlightList = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        lblTimeOfDay = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 56, 95, -1));

        lblSource.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSource.setForeground(new java.awt.Color(102, 0, 0));
        lblSource.setText("Source:");
        add(lblSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 59, 53, -1));

        lblDestination.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDestination.setForeground(new java.awt.Color(102, 0, 0));
        lblDestination.setText("Destination:");
        add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 115, 72, -1));
        add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 112, 95, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDate.setForeground(new java.awt.Color(102, 0, 0));
        lblDate.setText(" Date:");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 59, 59, -1));
        add(txtTimeOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 112, 127, -1));

        tblSearchFlightList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblSearchFlightList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Id", "Source", "Destination", "Date", "Time Of Day", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSearchFlightList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 179, 602, 74));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(102, 0, 0));
        btnSearch.setText("Search >>");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 286, 119, -1));

        lblTimeOfDay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimeOfDay.setForeground(new java.awt.Color(102, 0, 0));
        lblTimeOfDay.setText("Time Of Day:");
        add(lblTimeOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 112, 76, 20));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 56, 127, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Travel Agency Manager");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 16, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 320, 119, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat parser = new SimpleDateFormat("MM-dd-yyyy");
        Date flightDate = null;
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        String timeOfDay = txtTimeOfDay.getText();

        if (!source.isEmpty() && !destination.isEmpty() && !timeOfDay.isEmpty()) {
            try {
                flightDate = parser.parse(txtDate.getText());
                populateTable(source, destination, timeOfDay, flightDate);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please enter date in correct format MM-dd-yyyy");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter values for empty fields");
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTimeOfDay;
    private javax.swing.JTable tblSearchFlightList;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTimeOfDay;
    // End of variables declaration//GEN-END:variables
}
