/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Airline.Flight;
import Business.Customer.Customer;
import Business.Department.Department;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.User.User;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {
    private JPanel upc;
    private Customer customer;
    private EcoSystem business;
    private List<User> users;
    /**
     * Creates new form ManageCustomer
     */
    public ManageCustomerJPanel(JPanel upc, User user, EcoSystem business) {
        initComponents();
        this.upc = upc;
        this.customer = user.getCustomer();
        this.business = business;
        this.users = new ArrayList<>();
        populate();
        //System.out.println("Customer" + customer.getName());
        //System.out.println("Customeru" + user.getCustomer().getName());
    }

    
    public void populate(){
        countryComboBox.removeAllItems();
        List<Enterprise> exports = new ArrayList<>();
        for(Network network : business.getNetworkList()){
            for(Enterprise e: network.getEntList().getEnterpriseList()){
                if(e.getEntType() == Enterprise.EnterpriseType.Export){
                    exports.add(e);
                }
            }
        }
//        for(Enterprise enterprise : exports){
//            for(Department department : enterprise.getDepartmentList().getDepList()){
//                for(User user : department.getUserList().getUserList()){
//                    if(user.getEmployee().getFlight() != null){
//                        countryComboBox.addItem(user.getEmployee().getFlight());
//                        users.add(user);
        List<String> countryList = new ArrayList<>();
        for(Enterprise enterprise : exports){
            for(Department department : enterprise.getDepartmentList().getDepList()){
                for(User user : department.getUserList().getUserList()){
                    if(user.getEmployee().getFlight() != null){
                        if(!countryList.contains(user.getEmployee().getFlight().getCty())){
                          countryList.add(user.getEmployee().getFlight().getCty());
                    }
                }
            }
        }
      }
          for(String s : countryList){
            countryComboBox.addItem(s);
          }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("Select Country");

        countryComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        countryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryComboBoxActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("Next  >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Flight flight = (Flight)countryComboBox.getSelectedItem();
        String country = (String)countryComboBox.getSelectedItem();
        SelectEnterpriseJPanel sejp = new SelectEnterpriseJPanel(upc, country, customer, business);
        upc.add("manageOrganizationJPanel", sejp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void countryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox countryComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
