/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageCustomers;

import Business.Airliner;
import Business.FlightSchedule;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.manageAirliner.ViewAirlinerJPanel;

/**
 *
 * @author jhalak
 */
public class BestDealJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private TravelAgency travelAgency;

    /**
     * Creates new form BestDealJPanel
     */
    public BestDealJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
    }

    public void populateTable(String source, String destination, Date flightDate, String timeOfDay) {

        List<Integer> pricesList = new ArrayList<>();
        SimpleDateFormat parser = new SimpleDateFormat("MM-dd-yyyy");
        ArrayList<FlightSchedule> flightScheduleArrayList = travelAgency.getMasterScheduleDirectory().getMasterFlightSchedules();
        for (FlightSchedule ad : flightScheduleArrayList) {

            if (ad.getSource().equalsIgnoreCase(source)
                    && ad.getDestination().equalsIgnoreCase(destination)
                    && parser.format(ad.getFlightDate()).equalsIgnoreCase(txtDepartureDate.getText())
                    && ad.getTimeOfDay().equals(timeOfDay)) {
                pricesList.add(ad.getPrice());

            }

        }
        getMinimumPriceFlightAndDisplay(pricesList);
    }

    private void getMinimumPriceFlightAndDisplay(List<Integer> priceList) {
        DefaultTableModel dtm = (DefaultTableModel) tblCheapFlights.getModel();
        dtm.setRowCount(0);
        int minPrice = Collections.min(priceList);
        for (FlightSchedule ad : travelAgency.getMasterScheduleDirectory().getMasterFlightSchedules()) {
            if (ad.getPrice() == minPrice) {
                Object row[] = new Object[6];
                row[0] = ad;
                row[1] = ad.getAirlinerName();
                row[2] = ad.getSource();
                row[3] = ad.getDestination();
                row[4] = ad.getFlightDate();
                row[5] = ad.getPrice();
                dtm.addRow(row);

            }
        }

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        txtTimeOfDay = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtDepartureDate = new javax.swing.JTextField();
        lblTimeOfDay = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCheapFlights = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("BEST DEAL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 11, 101, -1));

        lblSource.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSource.setForeground(new java.awt.Color(102, 0, 0));
        lblSource.setText("Source:");
        add(lblSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Destination:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 118, -1, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDate.setForeground(new java.awt.Color(102, 0, 0));
        lblDate.setText("Departure Date:");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 163, -1, -1));
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 64, 101, -1));
        add(txtTimeOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 207, 101, -1));
        add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 115, 101, -1));

        txtDepartureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartureDateActionPerformed(evt);
            }
        });
        add(txtDepartureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 160, 101, -1));

        lblTimeOfDay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimeOfDay.setForeground(new java.awt.Color(102, 0, 0));
        lblTimeOfDay.setText("Time Of Day:");
        add(lblTimeOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 210, -1, -1));

        tblCheapFlights.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblCheapFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Id", "Airliner Name  ", "  Source", "  Destination", "Departure Date", " Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCheapFlights);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 270, 579, 60));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(102, 0, 0));
        btnSearch.setText("Search >>");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 206, -1, -1));

        btnSelect.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(102, 0, 0));
        btnSelect.setText("Please Select the flight");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 371, 167, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 371, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepartureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartureDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartureDateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat parser = new SimpleDateFormat("MM-dd-yyyy");
        Date flightDate = null;
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        String timeOfDay = txtTimeOfDay.getText();

        if (!source.isEmpty() && !destination.isEmpty() && !timeOfDay.isEmpty()) {
            try {
                flightDate = parser.parse(txtDepartureDate.getText());
                populateTable(source, destination, flightDate, timeOfDay);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please enter date in correct format MM-dd-yyyy");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter values for empty fields");
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblCheapFlights.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            FlightSchedule flight = (FlightSchedule) tblCheapFlights.getValueAt(selectedRow, 0);
            BookingCustomerJPanel bookCustomerJPanel = new BookingCustomerJPanel(userProcessContainer,flight,travelAgency);
            userProcessContainer.add("BookCustomerJPanel", bookCustomerJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTimeOfDay;
    private javax.swing.JTable tblCheapFlights;
    private javax.swing.JTextField txtDepartureDate;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTimeOfDay;
    // End of variables declaration//GEN-END:variables
}
