/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageCustomers;

import Business.Customer;
import Business.FlightSchedule;
import Business.Seat;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jhalak
 */
public class BookingCustomerJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private TravelAgency travelAgency;
    private FlightSchedule flights;
    Seat s=new Seat();

    /**
     * Creates new form BookingCustomerJPanel
     */
    public BookingCustomerJPanel(JPanel userProcessContainer,FlightSchedule flight, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
        this.flights=flight;
        populateDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        banner = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        txtFlightId = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtTimeOfDay = new javax.swing.JTextField();
        txtDepartureTime = new javax.swing.JTextField();
        lblDepartureDate = new javax.swing.JLabel();
        lblTimeOfDay1 = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblFlightId = new javax.swing.JLabel();
        Banner = new javax.swing.JLabel();
        btnBookingDetails = new javax.swing.JButton();
        txtTypeOfSeat = new javax.swing.JTextField();
        lblTypeOfSeat = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtFinalPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(102, 0, 0));
        lblCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerName.setText("Customer Name:");
        add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 83, -1, -1));

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAge.setForeground(new java.awt.Color(102, 0, 0));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 114, -1, -1));

        lblEmailAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmailAddress.setForeground(new java.awt.Color(102, 0, 0));
        lblEmailAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmailAddress.setText("Email:");
        add(lblEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 148, -1, -1));

        lblContactNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblContactNumber.setForeground(new java.awt.Color(102, 0, 0));
        lblContactNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContactNumber.setText("Contact Number:");
        add(lblContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 179, -1, -1));
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 80, 114, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 111, 114, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 142, 114, -1));
        add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 173, 114, -1));

        banner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        banner.setForeground(new java.awt.Color(0, 51, 102));
        banner.setText("Booking Details");
        add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 27, 180, -1));

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGender.setForeground(new java.awt.Color(102, 0, 0));
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 217, -1, -1));
        add(txtSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 211, 114, -1));

        txtFlightId.setEditable(false);
        txtFlightId.setEnabled(false);
        add(txtFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 353, 108, -1));

        txtPrice.setEditable(false);
        txtPrice.setEnabled(false);
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 397, 108, -1));

        txtSource.setEditable(false);
        txtSource.setEnabled(false);
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 441, 108, -1));

        txtDestination.setEditable(false);
        txtDestination.setEnabled(false);
        add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 483, 108, -1));

        txtTimeOfDay.setEditable(false);
        txtTimeOfDay.setEnabled(false);
        add(txtTimeOfDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 521, 108, -1));

        txtDepartureTime.setEditable(false);
        txtDepartureTime.setEnabled(false);
        add(txtDepartureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 559, 108, -1));

        lblDepartureDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDepartureDate.setForeground(new java.awt.Color(102, 0, 0));
        lblDepartureDate.setText("   Departure Time:");
        add(lblDepartureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 559, -1, -1));

        lblTimeOfDay1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTimeOfDay1.setForeground(new java.awt.Color(102, 0, 0));
        lblTimeOfDay1.setText("Time Of Day:");
        add(lblTimeOfDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 524, -1, -1));

        lblDestination.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDestination.setForeground(new java.awt.Color(102, 0, 0));
        lblDestination.setText("Destination:");
        add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 486, -1, -1));

        lblSource.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSource.setForeground(new java.awt.Color(102, 0, 0));
        lblSource.setText("Source:");
        add(lblSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 444, -1, -1));

        lblModelNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblModelNumber.setForeground(new java.awt.Color(102, 0, 0));
        lblModelNumber.setText("     Price:");
        add(lblModelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 400, 50, -1));

        lblFlightId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFlightId.setForeground(new java.awt.Color(102, 0, 0));
        lblFlightId.setText("Flight ID:");
        add(lblFlightId, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 356, -1, -1));

        Banner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Banner.setForeground(new java.awt.Color(0, 51, 102));
        Banner.setText("Your Selection");
        add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 321, 156, -1));

        btnBookingDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBookingDetails.setForeground(new java.awt.Color(102, 0, 0));
        btnBookingDetails.setText("Book Flight >>");
        btnBookingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingDetailsActionPerformed(evt);
            }
        });
        add(btnBookingDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 266, 167, -1));

        txtTypeOfSeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTypeOfSeatMouseClicked(evt);
            }
        });
        add(txtTypeOfSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 249, 114, -1));

        lblTypeOfSeat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTypeOfSeat.setForeground(new java.awt.Color(102, 0, 0));
        lblTypeOfSeat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTypeOfSeat.setText("Type Of Seat:");
        add(lblTypeOfSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 252, -1, -1));

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(102, 0, 0));
        lblPrice.setText("Final Price:");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 287, -1, -1));

        txtFinalPrice.setEnabled(false);
        add(txtFinalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 283, 114, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<< Back ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateDetails()
    {
        txtFlightId.setText(flights.getFlightId());
        txtPrice.setText(String.valueOf(flights.getPrice()));
        txtSource.setText(flights.getSource());
        txtDestination.setText(flights.getDestination());
        txtTimeOfDay.setText(flights.getTimeOfDay()); 
        txtDepartureTime.setText(String.valueOf(flights.getFlightDate()));
        
    }
    
    
    
    private void btnBookingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingDetailsActionPerformed
        // TODO add your handling code here:
        String customerName = txtCustomerName.getText();
        int Age = 0;
        String email = txtEmail.getText();
        long contactNumber = 0;
        String gender = txtSex.getText();
        String typeOfSeat=txtTypeOfSeat.getText();

        try {

            Age = Integer.parseInt(txtAge.getText());
            contactNumber = Long.parseLong(txtContactNumber.getText());
            if (!customerName.isEmpty() && !email.isEmpty()
                    && !gender.isEmpty() && Age != 0 && contactNumber != 0 && !typeOfSeat.isEmpty()) {
                Customer customer = travelAgency.getCustomerDirectory().addCustomerDetails();
                customer.setCustomerName(customerName);
                customer.setAge(Age);
                customer.setContactNumber(contactNumber);
                customer.setEmail(email);
                customer.setSex(gender);
               if(s!=null)
               {
                s=flights.addSeat();
                s.setTypeOfSeat(typeOfSeat);
                s.setCustomer(customer);
               }
                JOptionPane.showMessageDialog(null, "You have booked the flight successfully");

            } else {
                JOptionPane.showMessageDialog(null, "Please enter values for empty fields");
            }
        } catch (Exception exp) {
            JOptionPane.showMessageDialog(null, "Please enter integer value for contact number and age");
        }
    }//GEN-LAST:event_btnBookingDetailsActionPerformed

    private void txtTypeOfSeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTypeOfSeatMouseClicked
        // TODO add your handling code here:
        String x=txtTypeOfSeat.getText();
        s.setTypeOfSeat(x);
        txtFinalPrice.setText(String.valueOf(flights.getPrice()*s.getMargin()));              
    }//GEN-LAST:event_txtTypeOfSeatMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookingDetails;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDepartureDate;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFlightId;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTimeOfDay1;
    private javax.swing.JLabel lblTypeOfSeat;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDepartureTime;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFinalPrice;
    private javax.swing.JTextField txtFlightId;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTimeOfDay;
    private javax.swing.JTextField txtTypeOfSeat;
    // End of variables declaration//GEN-END:variables

}
